### ISSUE TITLE
Broken package ros-kinetic-pcl-conversions

### ISSUE THREAD

**Issue by skamdar** [ros-perception/pcl_conversions#27] opened 2018-03-10 19:45 UTC
I am trying to install ros-kinetic but it is showing following error:
dpkg: dependency problems prevent configuration of ros-kinetic-pcl-conversions:
 ros-kinetic-pcl-conversions depends on libpcl-dev; however:
  Package libpcl-dev is not installed

When I tried sudo apt-get install libpcl-dev it shows following:

E: /var/cache/apt/archives/libpcl-dev_1.7.2-14build1_amd64.deb: trying to overwrite '/usr/include/pcl-1.7/pcl/for_each_type.h', which is also in package libpcl-common-1.7-dev 1.7.2-1+trusty6

Please help!

**Comment by tfoote** [comment] 2018-03-12 05:10
This needs to be filed upstream with libpcl-dev that it is conflicting with libpcl-common-1.7-dev I think this is the right place to file it: https://bugs.launchpad.net/ubuntu/+source/pcl Though before you do, I'd double check that you don't have incompatilble sources. As the conflicting builds have different extensions which suggests that you might be using incorrect sources. In particular you have a package with "trusty" in the name conflicting which is not a supported platform for Kinetic. Which suggests you're either using Kinetic on an unsupported system(trusty) or have installed trusty builds on a (xenial?) machine.

**Comment by tfoote** [comment] 2018-03-12 05:11
Duplicate of: https://github.com/ros/rosdistro/issues/17100 multiple postings of issues is against our support guildelines. http://wiki.ros.org/Support

**Closed as completed by tfoote** 2018-03-12 05:11 UTC
